replicaCount: 2

image:
  repository: bestrong.azurecr.io/bestrong-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: kjk-s.xyz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: letsencrypt-prod-tls
      hosts:
        - kjk-s.xyz

certificate:
  enabled: true
  name: letsencrypt-prod-tls
  issuer: letsencrypt-prod
  secretName: letsencrypt-prod-tls
  dnsNames:
    - kjk-s.xyz

resources: {}
variables:
  azureContainerRegistry: 'bestrong'
  azureResourceGroup: 'rg-bestrong'
  imageRepository: 'bestrong-api'
  tag: '$(Build.BuildId)'
  dockerRegistryServiceConnection: 'bestrong-acr'
  azureRmServiceConnection: 'azure-conn'
