# beststrong-cert.yaml
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bestrong-cert
  namespace: default
spec:
  secretName: bestrong-tls
  duration: 2160h 
  renewBefore: 360h 
  subject:
    organizations:
      - BeStrong
  commonName: bestrong.20.185.209.18.nip.io
  dnsNames:
    - bestrong.20.185.209.18.nip.io
  issuerRef:
    name: selfsigned-clusterissuer
    kind: ClusterIssuer
