apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-challenge
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: kjk-s.xyz
    http:
      paths:
      - path: /.well-known/acme-challenge/
        pathType: ImplementationSpecific
        backend:
          service:
            name: test-challenge-service
            port:
              number: 80
---
apiVersion: v1
kind: Service
metadata:
  name: test-challenge-service
  namespace: default
spec:
  selector:
    app: test-challenge
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: test-challenge-pod
  namespace: default
  labels:
    app: test-challenge
spec:
  containers:
  - name: test-challenge
    image: hashicorp/http-echo
    args:
    - "-text=acme-test"
    - "-listen=:8080"
    ports:
    - containerPort: 8080
